package app.marlboroadvance.mpvex.utils.media

import android.content.Context
import android.net.Uri
import android.os.ParcelFileDescriptor
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import net.mediaarea.mediainfo.lib.MediaInfo

object MediaInfoOps {
  /**
   * Helper to open MediaInfo for any URI scheme (HTTP/HTTPS streaming, ContentProvider, file)
   * and ensure proper cleanup of native resources and file descriptors.
   */
  private inline fun <T> openMediaInfo(
    context: Context,
    uri: Uri,
    fileName: String = "",
    headers: Map<String, String> = emptyMap(),
    block: (MediaInfo) -> T,
  ): T {
    val mi = MediaInfo()
    try {
      val scheme = uri.scheme?.lowercase()
      when {
        scheme == "http" || scheme == "https" -> {
          val url = uri.toString()
          val effectiveName = if (fileName.isNotEmpty()) fileName else (uri.lastPathSegment ?: "stream")
          mi.Open(url = url, headers = headers, filename = effectiveName)
        }
        scheme == "content" -> {
          val pfd = context.contentResolver.openFileDescriptor(uri, "r")
            ?: throw java.io.FileNotFoundException("Could not open file descriptor for $uri")
          // Detach fd so Android's fdsan relinquishes ownership before native libmediainfo closes it
          val fd = pfd.detachFd()
          val effectiveName = if (fileName.isNotEmpty()) fileName else (uri.lastPathSegment ?: "")
          mi.Open(fd, effectiveName)
        }
        scheme == "file" || scheme == null -> {
          val path = uri.path ?: uri.toString()
          mi.Open(path)
        }
        else -> {
          mi.Open(uri.toString())
        }
      }
      return block(mi)
    } finally {
      try {
        mi.Close()
      } catch (_: Exception) {}
    }
  }

  /**
   * Extract detailed media information from a video file or network stream
   */
  suspend fun getMediaInfo(
    context: Context,
    uri: Uri,
    fileName: String,
    headers: Map<String, String> = emptyMap(),
  ): Result<MediaInfoData> =
    withContext(Dispatchers.IO) {
      runCatching {
        openMediaInfo(context, uri, fileName, headers) { mi ->
          val generalInfo = extractGeneralInfo(mi)
          val videoStreams = extractVideoStreams(mi)
          val audioStreams = extractAudioStreams(mi)
          val textStreams = extractTextStreams(mi)

          // Generate formatted text output in the same pass
          mi.Option("Inform", "Text")
          val textOutput = mi.Inform()
          val report = buildString {
            appendLine("=".repeat(60))
            appendLine("MEDIA INFO - $fileName")
            appendLine("=".repeat(60))
            appendLine()
            append(textOutput)
            appendLine()
            appendLine("=".repeat(60))
            appendLine("Generated by mpvex using MediaInfoLib")
            appendLine("=".repeat(60))
          }

          MediaInfoData(
            general = generalInfo,
            videoStreams = videoStreams,
            audioStreams = audioStreams,
            textStreams = textStreams,
            rawReport = report,
          )
        }
      }
    }

  /**
   * Generate formatted text output from MediaInfoData using native MediaInfo Text format
   */
  suspend fun generateTextOutput(
    context: Context,
    uri: Uri,
    fileName: String,
    headers: Map<String, String> = emptyMap(),
  ): Result<String> =
    withContext(Dispatchers.IO) {
      runCatching {
        openMediaInfo(context, uri, fileName, headers) { mi ->
          mi.Option("Inform", "Text")
          val textOutput = mi.Inform()

          buildString {
            appendLine("=".repeat(60))
            appendLine("MEDIA INFO - $fileName")
            appendLine("=".repeat(60))
            appendLine()
            append(textOutput)
            appendLine()
            appendLine("=".repeat(60))
            appendLine("Generated by mpvex using MediaInfoLib")
            appendLine("=".repeat(60))
          }
        }
      }
    }

  private fun MediaInfo.getInfo(
    stream: MediaInfo.Stream,
    index: Int,
    parameter: String,
  ): String = Get(stream, index, parameter)

  private fun extractGeneralInfo(mi: MediaInfo): GeneralInfo =
    GeneralInfo(
      completeName = mi.getInfo(MediaInfo.Stream.General, 0, "CompleteName"),
      format = mi.getInfo(MediaInfo.Stream.General, 0, "Format"),
      formatVersion = mi.getInfo(MediaInfo.Stream.General, 0, "Format_Version"),
      fileSize = mi.getInfo(MediaInfo.Stream.General, 0, "FileSize/String"),
      duration = mi.getInfo(MediaInfo.Stream.General, 0, "Duration/String3"),
      overallBitRate = mi.getInfo(MediaInfo.Stream.General, 0, "OverallBitRate/String"),
      frameRate = mi.getInfo(MediaInfo.Stream.General, 0, "FrameRate/String"),
      title = mi.getInfo(MediaInfo.Stream.General, 0, "Title"),
      encodedDate = mi.getInfo(MediaInfo.Stream.General, 0, "Encoded_Date"),
      writingApplication = mi.getInfo(MediaInfo.Stream.General, 0, "Encoded_Application/String"),
      writingLibrary = mi.getInfo(MediaInfo.Stream.General, 0, "Encoded_Library/String"),
    )

  private fun extractVideoStreams(mi: MediaInfo): List<VideoStreamInfo> {
    val count = mi.Count_Get(MediaInfo.Stream.Video)
    return (0 until count).map { i ->
      VideoStreamInfo(
        streamIndex = i,
        id = mi.getInfo(MediaInfo.Stream.Video, i, "ID"),
        format = mi.getInfo(MediaInfo.Stream.Video, i, "Format"),
        formatInfo = mi.getInfo(MediaInfo.Stream.Video, i, "Format/Info"),
        formatProfile = mi.getInfo(MediaInfo.Stream.Video, i, "Format_Profile"),
        codecId = mi.getInfo(MediaInfo.Stream.Video, i, "CodecID"),
        duration = mi.getInfo(MediaInfo.Stream.Video, i, "Duration/String3"),
        bitRate = mi.getInfo(MediaInfo.Stream.Video, i, "BitRate/String"),
        width = mi.getInfo(MediaInfo.Stream.Video, i, "Width/String"),
        height = mi.getInfo(MediaInfo.Stream.Video, i, "Height/String"),
        displayAspectRatio = mi.getInfo(MediaInfo.Stream.Video, i, "DisplayAspectRatio/String"),
        frameRate = mi.getInfo(MediaInfo.Stream.Video, i, "FrameRate/String"),
        frameRateMode = mi.getInfo(MediaInfo.Stream.Video, i, "FrameRate_Mode"),
        colorSpace = mi.getInfo(MediaInfo.Stream.Video, i, "ColorSpace"),
        chromaSubsampling = mi.getInfo(MediaInfo.Stream.Video, i, "ChromaSubsampling"),
        bitDepth = mi.getInfo(MediaInfo.Stream.Video, i, "BitDepth/String"),
        bitsPixelFrame = mi.getInfo(MediaInfo.Stream.Video, i, "Bits-(Pixel*Frame)"),
        streamSize = mi.getInfo(MediaInfo.Stream.Video, i, "StreamSize/String"),
        encodingLibrary = mi.getInfo(MediaInfo.Stream.Video, i, "Encoded_Library/String"),
        defaultStream = mi.getInfo(MediaInfo.Stream.Video, i, "Default/String"),
        forcedStream = mi.getInfo(MediaInfo.Stream.Video, i, "Forced/String"),
        hdrFormat = mi.getInfo(MediaInfo.Stream.Video, i, "HDR_Format"),
        maxCLL = mi.getInfo(MediaInfo.Stream.Video, i, "MaxCLL"),
        maxFALL = mi.getInfo(MediaInfo.Stream.Video, i, "MaxFALL"),
      )
    }
  }

  private fun extractAudioStreams(mi: MediaInfo): List<AudioStreamInfo> {
    val count = mi.Count_Get(MediaInfo.Stream.Audio)
    return (0 until count).map { i ->
      AudioStreamInfo(
        streamIndex = i,
        id = mi.getInfo(MediaInfo.Stream.Audio, i, "ID"),
        format = mi.getInfo(MediaInfo.Stream.Audio, i, "Format"),
        formatInfo = mi.getInfo(MediaInfo.Stream.Audio, i, "Format/Info"),
        codecId = mi.getInfo(MediaInfo.Stream.Audio, i, "CodecID"),
        duration = mi.getInfo(MediaInfo.Stream.Audio, i, "Duration/String3"),
        bitRate = mi.getInfo(MediaInfo.Stream.Audio, i, "BitRate/String"),
        channels = mi.getInfo(MediaInfo.Stream.Audio, i, "Channel(s)/String"),
        channelLayout = mi.getInfo(MediaInfo.Stream.Audio, i, "ChannelLayout"),
        samplingRate = mi.getInfo(MediaInfo.Stream.Audio, i, "SamplingRate/String"),
        frameRate = mi.getInfo(MediaInfo.Stream.Audio, i, "FrameRate/String"),
        compressionMode = mi.getInfo(MediaInfo.Stream.Audio, i, "Compression_Mode"),
        delay = mi.getInfo(MediaInfo.Stream.Audio, i, "Video_Delay/String3"),
        streamSize = mi.getInfo(MediaInfo.Stream.Audio, i, "StreamSize/String"),
        title = mi.getInfo(MediaInfo.Stream.Audio, i, "Title"),
        language = mi.getInfo(MediaInfo.Stream.Audio, i, "Language/String"),
        defaultStream = mi.getInfo(MediaInfo.Stream.Audio, i, "Default/String"),
        forcedStream = mi.getInfo(MediaInfo.Stream.Audio, i, "Forced/String"),
      )
    }
  }

  private fun extractTextStreams(mi: MediaInfo): List<TextStreamInfo> {
    val count = mi.Count_Get(MediaInfo.Stream.Text)
    return (0 until count).map { i ->
      TextStreamInfo(
        streamIndex = i,
        id = mi.getInfo(MediaInfo.Stream.Text, i, "ID"),
        format = mi.getInfo(MediaInfo.Stream.Text, i, "Format"),
        muxingMode = mi.getInfo(MediaInfo.Stream.Text, i, "MuxingMode"),
        codecId = mi.getInfo(MediaInfo.Stream.Text, i, "CodecID"),
        codecIdInfo = mi.getInfo(MediaInfo.Stream.Text, i, "CodecID/Info"),
        duration = mi.getInfo(MediaInfo.Stream.Text, i, "Duration/String3"),
        bitRate = mi.getInfo(MediaInfo.Stream.Text, i, "BitRate/String"),
        frameRate = mi.getInfo(MediaInfo.Stream.Text, i, "FrameRate/String"),
        countOfElements = mi.getInfo(MediaInfo.Stream.Text, i, "ElementCount"),
        streamSize = mi.getInfo(MediaInfo.Stream.Text, i, "StreamSize/String"),
        title = mi.getInfo(MediaInfo.Stream.Text, i, "Title"),
        language = mi.getInfo(MediaInfo.Stream.Text, i, "Language/String"),
        defaultStream = mi.getInfo(MediaInfo.Stream.Text, i, "Default/String"),
        forcedStream = mi.getInfo(MediaInfo.Stream.Text, i, "Forced/String"),
      )
    }
  }

  data class MediaInfoData(
    val general: GeneralInfo,
    val videoStreams: List<VideoStreamInfo>,
    val audioStreams: List<AudioStreamInfo>,
    val textStreams: List<TextStreamInfo>,
    val rawReport: String = "",
  ) {
    companion object {
      fun empty() =
        MediaInfoData(
          general = GeneralInfo(),
          videoStreams = emptyList(),
          audioStreams = emptyList(),
          textStreams = emptyList(),
          rawReport = "",
        )
    }
  }

  data class MediaDetails(
    val format: String,
    val durationMs: Long,
    val overallBitRate: String,
    val videoCodec: String,
    val videoProfile: String,
    val videoWidth: Int,
    val videoHeight: Int,
    val frameRate: String,
    val hdrFormat: String,
    val audioCodec: String,
    val audioChannels: String,
    val audioBitRate: String,
    val audioTrackCount: Int,
    val subtitleTrackCount: Int,
  )

  /**
   * Queries specific structured metadata parameters from the media stream.
   */
  suspend fun getMediaDetails(
    context: Context,
    uri: Uri,
    headers: Map<String, String> = emptyMap(),
  ): Result<MediaDetails> =
    withContext(Dispatchers.IO) {
      runCatching {
        openMediaInfo(context, uri, "", headers) { mi ->
          MediaDetails(
            format = mi.getInfo(MediaInfo.Stream.General, 0, "Format"),
            durationMs = mi.getInfo(MediaInfo.Stream.General, 0, "Duration").toDoubleOrNull()?.toLong() ?: 0L,
            overallBitRate = mi.getInfo(MediaInfo.Stream.General, 0, "OverallBitRate/String"),
            videoCodec = mi.getInfo(MediaInfo.Stream.Video, 0, "Format"),
            videoProfile = mi.getInfo(MediaInfo.Stream.Video, 0, "Format_Profile"),
            videoWidth = mi.getInfo(MediaInfo.Stream.Video, 0, "Width").toIntOrNull() ?: 0,
            videoHeight = mi.getInfo(MediaInfo.Stream.Video, 0, "Height").toIntOrNull() ?: 0,
            frameRate = mi.getInfo(MediaInfo.Stream.Video, 0, "FrameRate/String"),
            hdrFormat = mi.getInfo(MediaInfo.Stream.Video, 0, "HDR_Format"),
            audioCodec = mi.getInfo(MediaInfo.Stream.Audio, 0, "Format"),
            audioChannels = mi.getInfo(MediaInfo.Stream.Audio, 0, "Channel(s)/String"),
            audioBitRate = mi.getInfo(MediaInfo.Stream.Audio, 0, "BitRate/String"),
            audioTrackCount = mi.Count_Get(MediaInfo.Stream.Audio),
            subtitleTrackCount = mi.Count_Get(MediaInfo.Stream.Text),
          )
        }
      }
    }

  data class GeneralInfo(
    val completeName: String = "",
    val format: String = "",
    val formatVersion: String = "",
    val fileSize: String = "",
    val duration: String = "",
    val overallBitRate: String = "",
    val frameRate: String = "",
    val title: String = "",
    val encodedDate: String = "",
    val writingApplication: String = "",
    val writingLibrary: String = "",
  )

  data class VideoStreamInfo(
    val streamIndex: Int,
    val id: String = "",
    val format: String = "",
    val formatInfo: String = "",
    val formatProfile: String = "",
    val codecId: String = "",
    val duration: String = "",
    val bitRate: String = "",
    val width: String = "",
    val height: String = "",
    val displayAspectRatio: String = "",
    val frameRate: String = "",
    val frameRateMode: String = "",
    val colorSpace: String = "",
    val chromaSubsampling: String = "",
    val bitDepth: String = "",
    val bitsPixelFrame: String = "",
    val streamSize: String = "",
    val encodingLibrary: String = "",
    val defaultStream: String = "",
    val forcedStream: String = "",
    val hdrFormat: String = "",
    val maxCLL: String = "",
    val maxFALL: String = "",
  )

  data class AudioStreamInfo(
    val streamIndex: Int,
    val id: String = "",
    val format: String = "",
    val formatInfo: String = "",
    val codecId: String = "",
    val duration: String = "",
    val bitRate: String = "",
    val channels: String = "",
    val channelLayout: String = "",
    val samplingRate: String = "",
    val frameRate: String = "",
    val compressionMode: String = "",
    val delay: String = "",
    val streamSize: String = "",
    val title: String = "",
    val language: String = "",
    val defaultStream: String = "",
    val forcedStream: String = "",
  )

  data class TextStreamInfo(
    val streamIndex: Int,
    val id: String = "",
    val format: String = "",
    val muxingMode: String = "",
    val codecId: String = "",
    val codecIdInfo: String = "",
    val duration: String = "",
    val bitRate: String = "",
    val frameRate: String = "",
    val countOfElements: String = "",
    val streamSize: String = "",
    val title: String = "",
    val language: String = "",
    val defaultStream: String = "",
    val forcedStream: String = "",
  )

  /**
   * Quickly extract just size, duration, resolution, and framerate metadata from a video file or stream
   * Uses MediaInfo library which is faster and more reliable than MediaMetadataRetriever.
   *
   * @param context Android context
   * @param uri URI of the video file or stream
   * @param fileName Name of the file (needed for MediaInfo to detect format correctly)
   * @param headers Optional HTTP headers for network streams
   * @return Result containing VideoMetadata with size in bytes, duration in milliseconds, resolution, and fps
   */
  suspend fun extractBasicMetadata(
    context: Context,
    uri: Uri,
    fileName: String,
    headers: Map<String, String> = emptyMap(),
  ): Result<VideoMetadata> =
    withContext(Dispatchers.IO) {
      runCatching {
        openMediaInfo(context, uri, fileName, headers) { mi ->
          // Extract file size in bytes
          val fileSizeStr = mi.getInfo(MediaInfo.Stream.General, 0, "FileSize")
          val fileSize = fileSizeStr.toLongOrNull() ?: 0L

          // Extract duration in milliseconds - handle both integer and decimal formats
          val durationStr = mi.getInfo(MediaInfo.Stream.General, 0, "Duration")
          val duration = durationStr.toDoubleOrNull()?.toLong() ?: 0L

          // Extract video resolution (width and height)
          val widthStr = mi.getInfo(MediaInfo.Stream.Video, 0, "Width")
          val width = widthStr.toIntOrNull() ?: 0

          val heightStr = mi.getInfo(MediaInfo.Stream.Video, 0, "Height")
          val height = heightStr.toIntOrNull() ?: 0

          // Extract framerate (fps)
          val fpsStr = mi.getInfo(MediaInfo.Stream.Video, 0, "FrameRate")
          val fps = fpsStr.toFloatOrNull() ?: 0f

          val textCount = mi.Count_Get(MediaInfo.Stream.Text)
          val hasEmbeddedSubtitles = textCount > 0

          val subtitleCodec = if (hasEmbeddedSubtitles) {
            val codecs = mutableSetOf<String>()
            for (i in 0 until textCount) {
              val codecId = mi.getInfo(MediaInfo.Stream.Text, i, "CodecID")

              val normalizedCodec = when {
                codecId.contains("PGS", ignoreCase = true) -> "PGS"
                codecId.contains("ASS", ignoreCase = true) -> "ASS"
                codecId.contains("SSA", ignoreCase = true) -> "SSA"
                codecId.contains("SRT", ignoreCase = true) -> "SRT"
                codecId.contains("SUBRIP", ignoreCase = true) -> "SRT"
                codecId.contains("VOBSUB", ignoreCase = true) -> "DVD"
                codecId.contains("WEBVTT", ignoreCase = true) -> "VTT"
                codecId.contains("UTF8", ignoreCase = true) -> "SRT"
                codecId.contains("HDMV", ignoreCase = true) -> "PGS"
                codecId.contains("DVB", ignoreCase = true) -> "DVB"
                codecId.contains("MOV_TEXT", ignoreCase = true) -> "TX3G"
                codecId.isNotEmpty() -> {
                  codecId.substringAfterLast("/").substringAfterLast("_").uppercase()
                }
                else -> ""
              }

              if (normalizedCodec.isNotEmpty()) {
                codecs.add(normalizedCodec)
              }
            }
            codecs.joinToString(" ")
          } else ""

          VideoMetadata(fileSize, duration, width, height, fps, hasEmbeddedSubtitles, subtitleCodec)
        }
      }
    }

  /**
   * Data class to hold basic video metadata (size, duration, resolution, and framerate)
   */
  data class VideoMetadata(
    val sizeBytes: Long,
    val durationMs: Long,
    val width: Int,
    val height: Int,
    val fps: Float,
    val hasEmbeddedSubtitles: Boolean,
    val subtitleCodec: String = "",
  )

  /**
   * Extract rotation (in degrees) from the video stream. Returns 0 if not specified or on error.
   */
  suspend fun getRotation(
    context: Context,
    uri: Uri,
    fileName: String = "",
    headers: Map<String, String> = emptyMap(),
  ): Int = withContext(Dispatchers.IO) {
    runCatching {
      openMediaInfo(context, uri, fileName, headers) { mi ->
        val rotationStr = mi.Get(MediaInfo.Stream.Video, 0, "Rotation")
        rotationStr.toFloatOrNull()?.toInt() ?: 0
      }
    }.getOrDefault(0)
  }
}
