#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""一次性把硬编码英文 UI 文案抽成字符串资源（中英双语）。

为什么要用脚本：98 条文案分布在 40+ 个文件里，逐条手改既慢又容易漏掉 import。
脚本只处理三种「参数就是字符串字面量」的安全形态：
    Text(text = "…") / Text("…") / contentDescription = "…"
其它带插值（$xxx）或需要复数的文案不在本脚本范围内，另行手工处理。
"""
import os
import re

ROOT = r"D:\project\mpvEx-master\app\src\main"
JAVA = os.path.join(ROOT, "java")
EN_XML = os.path.join(ROOT, "res", "values", "strings.xml")
ZH_XML = os.path.join(ROOT, "res", "values-zh-rCN", "strings.xml")

# 英文原文 -> (资源键, 中文译文)
# 刻意跳过：Hello World / SPOjao;sjd（预览占位文本）、1:06 • Chapter 1、
# Video Title（预览示例）、github 链接、Logcat:
M = {
    "ALLOW ACCESS": ("i18n_allow_access", "允许访问"),
    "Add Custom Ratio (e.g. 16:9)": ("i18n_add_custom_ratio", "添加自定义比例（如 16:9）"),
    "Add M3U Playlist": ("i18n_add_m3u_playlist", "添加 M3U 播放列表"),
    "Add M3U Playlist from URL": ("i18n_add_m3u_from_url", "从网址导入 M3U 播放列表"),
    "Add Network Connection": ("i18n_add_network_connection", "添加网络连接"),
    "Add SMB, FTP, or WebDAV connections to browse network files": (
        "i18n_network_empty_hint", "添加 SMB、FTP 或 WebDAV 连接，即可浏览网络文件"),
    "Add to Playlist": ("i18n_add_to_playlist", "添加到播放列表"),
    "Add videos to get started": ("i18n_playlist_add_hint", "添加视频即可开始使用"),
    "All available buttons are in use.": ("i18n_layout_all_used", "所有可用按钮都已在使用中。"),
    "Also delete original file(s)": ("i18n_also_delete_original", "同时删除原始文件"),
    "Analyzing media file...": ("i18n_mediainfo_analyzing", "正在分析媒体文件…"),
    "Aspect Ratio": ("i18n_aspect_ratio", "画面比例"),
    "Auto Check for Updates": ("i18n_auto_check_updates", "自动检查更新"),
    "Automatically enter PIP mode when pressing home or back": (
        "i18n_auto_pip_hint", "按 Home 或返回键时自动进入画中画"),
    "Autoplay next video": ("i18n_autoplay_next_video", "自动播放下一集"),
    "Cannot select the same folder": ("i18n_folder_same", "不能选择同一个文件夹"),
    "Check on startup": ("i18n_check_on_startup", "启动时检查"),
    "Clear config cache": ("i18n_clear_config_cache", "清除配置缓存"),
    "Clear the cached mpv.conf settings": ("i18n_clear_config_cache_hint", "清除已缓存的 mpv.conf 设置"),
    "Clear thumbnail cache": ("i18n_clear_thumb_cache", "清除缩略图缓存"),
    "Connect automatically on app launch": ("i18n_connect_on_launch", "启动应用时自动连接"),
    "Create Empty Playlist": ("i18n_create_empty_playlist", "创建空白播放列表"),
    "Create New Folder": ("i18n_create_new_folder", "新建文件夹"),
    "Create New Playlist": ("i18n_create_new_playlist", "新建播放列表"),
    "Create a new blank playlist": ("i18n_create_blank_playlist_hint", "创建一个新的空白播放列表"),
    "Create folder": ("i18n_create_folder", "新建文件夹"),
    "Create your first playlist above": ("i18n_create_first_playlist", "在上方创建你的第一个播放列表"),
    "Decrease zoom": ("i18n_decrease_zoom", "缩小"),
    "Delete all cached video thumbnails (will regenerate as you browse folders)": (
        "i18n_clear_thumb_cache_hint", "删除所有已缓存的视频缩略图（浏览文件夹时会重新生成）"),
    "Device Info": ("i18n_device_info", "设备信息"),
    "Done reordering": ("i18n_done_reordering", "完成排序"),
    "Double Tap Seek Area Width": ("i18n_double_tap_area_width", "双击快进区域宽度"),
    "Downloading...": ("i18n_downloading", "正在下载…"),
    "Drag to reorder": ("i18n_drag_to_reorder", "拖动可排序"),
    "Drop zone is empty": ("i18n_layout_drop_empty", "放置区为空"),
    "Edit Connection": ("i18n_edit_connection", "编辑连接"),
    "Enable next/previous navigation": ("i18n_enable_nav", "启用上一集／下一集导航"),
    "Enter custom hide time in milliseconds": ("i18n_enter_hide_ms", "输入自定义隐藏时间（毫秒）"),
    "Enter custom seek duration in seconds (1-120)": ("i18n_enter_seek_seconds", "输入自定义快进时长（秒，1-120）"),
    "Existing Playlists": ("i18n_existing_playlists", "已有播放列表"),
    "Export Settings": ("i18n_export_settings", "导出设置"),
    "Export settings to an XML file": ("i18n_export_settings_hint", "把设置导出为 XML 文件"),
    "Folder Grid": ("i18n_folder_grid", "文件夹网格"),
    "Frame: ": ("i18n_frame_label", "帧："),
    "Generated by mpvEx using MediaInfoLib": ("i18n_mediainfo_footer", "由 mpvEx 使用 MediaInfoLib 生成"),
    "Go back": ("i18n_go_back", "返回上级"),
    "Go to internal storage": ("i18n_go_internal_storage", "前往内部存储"),
    "Grid Columns": ("i18n_grid_columns", "网格列数"),
    "Icons Legend": ("i18n_icons_legend", "图标说明"),
    "Import Settings": ("i18n_import_settings", "导入设置"),
    "Import a playlist from a web URL": ("i18n_import_m3u_hint", "从网络地址导入播放列表"),
    "Import settings from an XML file": ("i18n_import_settings_hint", "从 XML 文件导入设置"),
    "Increase zoom": ("i18n_increase_zoom", "放大"),
    "Invalid URL": ("i18n_invalid_url", "网址无效"),
    "Invalid URL protocol": ("i18n_invalid_url_protocol", "网址协议不受支持"),
    "Local Network": ("i18n_local_network", "局域网"),
    "Logcat:": ("i18n_logcat", "日志："),
    "Long press to reorder items. Tap the '-' icon to remove them.": (
        "i18n_layout_help", "长按可拖动排序，点击“-”图标移除。"),
    "Media Info": ("i18n_media_info", "媒体信息"),
    "Moved to Private Space": ("i18n_moved_private_space", "已移入隐私空间"),
    "No network connections": ("i18n_no_network_connections", "暂无网络连接"),
    "No subfolders": ("i18n_no_subfolders", "没有子文件夹"),
    "No videos found": ("i18n_no_videos_found", "未找到视频"),
    "No videos in playlist": ("i18n_no_videos_in_playlist", "播放列表中没有视频"),
    "Not available for 4K/8K video": ("i18n_not_available_4k8k", "4K/8K 视频不支持此功能"),
    "Now Playing": ("i18n_now_playing", "正在播放"),
    "Open File": ("i18n_open_file", "打开文件"),
    "Open Link": ("i18n_open_link", "打开链接"),
    "Pan & Zoom": ("i18n_pan_zoom", "平移与缩放"),
    "Play Link": ("i18n_play_link", "播放链接"),
    "Playlist Options": ("i18n_playlist_options", "播放列表选项"),
    "Quick Presets": ("i18n_quick_presets", "快捷预设"),
    "Remove all cached subtitle fonts": ("i18n_clear_font_cache_hint", "清除所有已缓存的字幕字体"),
    "Remove from Playlist": ("i18n_remove_from_playlist", "从播放列表中移除"),
    "Reorder playlist": ("i18n_reorder_playlist", "调整播放列表顺序"),
    "Reset to default": ("i18n_reset_default", "恢复默认"),
    "Search videos": ("i18n_search_videos", "搜索视频"),
    "Select Folder": ("i18n_select_folder", "选择文件夹"),
    "Select Subtitle": ("i18n_select_subtitle", "选择字幕"),
    "Show advance overlay for speed control during long press and swipe": (
        "i18n_speed_overlay_hint", "长按或滑动调速时显示进度浮层"),
    "Slide to Unlock": ("i18n_slide_to_unlock", "滑动解锁"),
    "Sort by": ("i18n_sort_by", "排序方式"),
    "Storage Access Required": ("i18n_storage_required", "需要存储访问权限"),
    "Stream Link": ("i18n_stream_link", "流媒体链接"),
    "Tap buttons from the 'Available Palette' below": (
        "i18n_layout_palette_hint", "从下方“可用按钮”中点选添加"),
    "Tap to edit configuration": ("i18n_tap_to_edit_config", "点击编辑配置"),
    "The permission is used exclusively for:": ("i18n_permission_usage", "该权限仅用于："),
    "Timestamp: ": ("i18n_timestamp_label", "时间戳："),
    "Unsaved changes": ("i18n_unsaved_changes", "有未保存的更改"),
    "Valid URL": ("i18n_valid_url", "网址有效"),
    "Video Grid": ("i18n_video_grid", "视频网格"),
    "Why do I see this?": ("i18n_why_see_this", "为什么会出现这个提示？"),
    "Why this permission is needed": ("i18n_why_permission", "为什么需要该权限"),
    # ── 单字/常用词（多为 contentDescription 与短按钮）──
    "Play": ("i18n_play", "播放"),
    "Search": ("i18n_search", "搜索"),
    "Settings": ("i18n_settings", "设置"),
    "Edit": ("i18n_edit", "编辑"),
    "Copy": ("i18n_copy", "复制"),
    "Share": ("i18n_share", "分享"),
    "Back": ("i18n_back", "返回"),
    "Thumbnail": ("i18n_thumbnail", "缩略图"),
    "Folder": ("i18n_folder", "文件夹"),
    "Move": ("i18n_move", "移动"),
    "None": ("i18n_none", "无"),
    "Connecting": ("i18n_connecting", "连接中"),
    "Separator": ("i18n_separator", "分隔符"),
    "Clear": ("i18n_clear", "清除"),
    "Save": ("i18n_save", "保存"),
    "Ignore": ("i18n_ignore", "忽略"),
    "Cancel": ("i18n_cancel", "取消"),
}

STR_RX = "\u0001"  # 变量名占位，避免 f-string 转义困扰


def esc_xml(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("'", "\\'")


def main():
    # 1) 写入两个 strings.xml
    def insert(path, is_zh):
        src = open(path, encoding="utf-8").read()
        lines = []
        for en, (key, zh) in M.items():
            if f'name="{key}"' in src:
                continue
            val = zh if is_zh else en
            lines.append(f'  <string name="{key}">{esc_xml(val)}</string>')
        if not lines:
            print(f"  {os.path.basename(path)}: 无需新增")
            return 0
        idx = src.rstrip().rfind("</resources>")
        src = src[:idx] + "\n".join(lines) + "\n" + src[idx:]
        open(path, "w", encoding="utf-8", newline="\n").write(src)
        print(f"  {os.path.basename(path)}: 新增 {len(lines)} 条")
        return len(lines)

    print("== 写入字符串资源 ==")
    insert(EN_XML, False)
    insert(ZH_XML, True)

    # 2) 替换 Kotlin
    print("\n== 替换 Kotlin 硬编码 ==")
    total = 0
    changed_files = 0
    for dp, _, fs in os.walk(JAVA):
        for f in fs:
            if not f.endswith(".kt"):
                continue
            p = os.path.join(dp, f)
            src = open(p, encoding="utf-8").read()
            orig = src
            n = 0
            for en, (key, _zh) in M.items():
                q = re.escape(en)
                # 1) 命名参数 text = "…"（Text / BasicText 等 Composable 的文案参数）
                rx1 = re.compile(r'text\s*=\s*"' + q + r'"')
                src, c1 = rx1.subn(f"text = stringResource(R.string.{key})", src)
                # 2) 位置参数 Text("…") —— 允许后面还有别的参数
                rx2 = re.compile(r'Text\(\s*"' + q + r'"')
                src, c2 = rx2.subn(f"Text(stringResource(R.string.{key})", src)
                # 3) 无障碍描述
                rx3 = re.compile(r'contentDescription\s*=\s*"' + q + r'"')
                src, c3 = rx3.subn(f"contentDescription = stringResource(R.string.{key})", src)
                n += c1 + c2 + c3
            if src == orig:
                continue
            # 补 import（仅在确实用到 stringResource 时）
            if "stringResource(" in src:
                if "import androidx.compose.ui.res.stringResource" not in src:
                    src = src.replace(
                        "import androidx.compose.ui.Modifier",
                        "import androidx.compose.ui.Modifier\nimport androidx.compose.ui.res.stringResource",
                        1,
                    )
                if "import app.marlboroadvance.mpvex.R\n" not in src:
                    m = re.search(r"^import app\.marlboroadvance\.mpvex\..*$", src, re.M)
                    if m:
                        src = src[:m.start()] + "import app.marlboroadvance.mpvex.R\n" + src[m.start():]
                    else:
                        m2 = re.search(r"^import ", src, re.M)
                        src = src[:m2.start()] + "import app.marlboroadvance.mpvex.R\n" + src[m2.start():]
            open(p, "w", encoding="utf-8", newline="\n").write(src)
            rel = os.path.relpath(p, JAVA)
            print(f"  {rel}: {n} 处")
            total += n
            changed_files += 1

    print(f"\n合计替换 {total} 处，涉及 {changed_files} 个文件")


if __name__ == "__main__":
    main()
